version: '3.0'

services:
  ng-development:
    image: ng-development
    container_name: ng-development
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    network_mode: "host"